### ISSUE TITLE
Enable User details updation

### ISSUE THREAD

**Issue by ghost** [Promact/slack-erp-custom-integration-mvc#100]
When we add Slack Username and it does not match with the username in the slack, So we are not able to change it.
We have the function implemented for the edit but it is not been updated in the database.

**Comment by juliepromact** [comment]
The best way to solve this isssue is to store the SlackUserId instead of SlackUserName. 

For doing so we have to make changes in the [Promact OAuth's](https://github.com/Promact/promact-oauth-server) User Add functionality. At present SlackUserName is saved while adding a user, instead add SlackUserId.
So fetching by SlackUserName will be replaced by fetching by SlackUserId in every functionality of [Promact SCI Project](https://github.com/Promact/slack-erp-custom-integration-mvc) . In doing so we become independant of the changes in SlackUserName.

**Comment by chintans** [comment]
Agreed, Please implement

**Comment by juliepromact** [comment]
Yes. This will require some time. Corresponding changes have to be done by @gouravagrwal and @siddharthashw in their respective modules.

**Comment by juliepromact** [comment]
Estimated time : 16 hours
Start date : 21-11-2016
End Date : 22-11-2016
